// We can get JavaScript Output in 4 simple and different ways on a webpage and these are given below.

//Using an alert Box 
alert('Hello')


//Using document.write()
document.write("Today you're doing a great job!")
document.write('Result = ' + (10+40) )

//Using the console.log()
//However this output will be found in the console tab of Chrome 
console.log("Hey you've found me!!")

//Using the innerHtml tag
document.getElementById('p1').innerHTML = "OOps we've changed the P1 original tag"